### ISSUE TITLE
Search Tasks

### ISSUE THREAD

**Issue by longthb3112** [longthb3112/MWA-project#2]
- Search Text for name and description
- by properties: priority, duedate, status

**Comment by SunenaGwachha** [comment]
working on it...

**Comment by SunenaGwachha** [comment]
completed "search tasks"
[MWA-project-master.zip](https://github.com/longthb3112/MWA-project/files/3746141/MWA-project-master.zip)

**Comment by SunenaGwachha** [comment]
task1 completed...
